Repository AjuntamentdeBarcelona/decidim-barcelona, pull requests merged in 2025-04, with the labels that each got.

#612 Restore deleted methods by decidim used in overridden views
  app/helpers/concerns/decidim/accountability/application_helper_override.rb
  config/initializers/decidim_overrides.rb
  spec/lib/overrides_spec.rb
Labels: bug

#611 Vote on proposal from listing page
  Gemfile
  Gemfile.lock
  spec/lib/overrides_spec.rb
Labels: dependencies, ruby

#614 Add capistrano gems
  Gemfile
  Gemfile.lock
Labels: dependencies

#615 Custom WickedPdf initializer
  config/initializers/wicked_pdf.rb
Labels: bug

#613 Use `dotenv-rails` gem on production too
  Gemfile
Labels: dependencies

#617 Downgrade `wicked_pdf` from 2.8.0 to 2.7.0
  Gemfile
  Gemfile.lock
  config/initializers/wicked_pdf.rb
Labels: dependencies, ruby

#621 Install whenever to manage cron jobs
  Gemfile
  Gemfile.lock
  config/schedule.rb
Labels: dependencies, ruby
